### PR TITLE
feat: add script as PowerShell

### PR DESCRIPTION
**Pull request by lechnerc77**
This PR adds a PowerShell version of the already existing script to enable Windows users to also check their setup using PowerShell.

Due to the PowerShell Syntax some formatting adjustments were made (like not supported "Bold" in PS).

The PR also contains the extension of the `README.md` to consider the new script flavor.

### CODE REVIEW

**Review by fleischr — APPROVED** [review]

**Comment by fleischr** [comment]
Hey @lechnerc77 great contribution! while testing I did stray into some special characters issue with the ascii art in the powershell script though.

**Comment by lechnerc77** [comment]
Hi @fleischr , can you point me how to reproduce that. Is it in the pictures that get deisplayed or the regular output from the commands? Which PowerShell version are you using?

**Comment by fleischr** [comment]
Hey @lechnerc77 - I was on powershell version 5.1.

I'm going to update it and see if that fixes any issues with special character handling I was having

**Comment by lechnerc77** [comment]
Hi @fleischr I see. I tested it on 7.4.2. I personally think that it makes sense to exclusively support the cross-platform version of PowerShell in accordance to its supported versions (see <https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.4>). 

Although the old Windows PowerShell 5.x as component of Windows is still supported I think this will be painful to get things going there.  Let me know what you think and if you could still see the issue with the newer version of PowerShell.

**Comment by fleischr** [comment]
Hi @lechnerc77 - I had found it to be the same on powershell 5.1 and 7. I've gone ahead and merged this PR and followed up with a few fixes. Thanks!

**Pull request merged**
